import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Manually-authored Firebase config (not generated by `flutterfire configure`,
/// which needs an interactive Google login this project's build environment
/// doesn't have). Values come straight from the Firebase console — the API
/// key here is not a secret; Firebase's security model is the Realtime
/// Database Rules, not hiding this config.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDllbfB9x_hYefIOH702otMKX-Mzk8nXqE',
    appId: '1:408927112981:android:c7cf9d88274003a1d1231c',
    messagingSenderId: '408927112981',
    projectId: 'ecosystem-controller',
    databaseURL: 'https://ecosystem-controller-default-rtdb.firebaseio.com',
    storageBucket: 'ecosystem-controller.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmIOfbe1nA3c3NAFRZwBwK9FykqYkn27M',
    appId: '1:408927112981:web:4fbc848e12b8461ad1231c',
    messagingSenderId: '408927112981',
    projectId: 'ecosystem-controller',
    authDomain: 'ecosystem-controller.firebaseapp.com',
    databaseURL: 'https://ecosystem-controller-default-rtdb.firebaseio.com',
    storageBucket: 'ecosystem-controller.firebasestorage.app',
  );
}
